<?xml version="1.0" ?>
<xsl:transform version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:wix="http://schemas.microsoft.com/wix/2006/wi">

  <!-- copy all as is -->
  <xsl:template match="@*|*">
    <xsl:copy>
      <xsl:apply-templates select="@*|*" />
    </xsl:copy>
  </xsl:template>

  <!-- FIXME: How to separate File and TypeLib? -->
  <!-- Add TypeLib tag to gvim.exe's File tag -->
  <xsl:template match="wix:File[contains(@Source, 'gvim.exe')]">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()" />
      <xsl:text disable-output-escaping="yes">
        <![CDATA[
        <?if $(env.FEAT_OLE) = 1?>
        <!--
          This component installs OLE typelib (Same as gvim.exe -register).
          TypeLib and Interface are generated by "heat.exe file vim\src\vim.tlb".
          See vim\src\if_ole.idl for id.
        -->
        <TypeLib Id="{0F0BFAE0-4C90-11D1-82D7-0004AC368519}" Description="Vim OLE Interface 1.1 Type Library" Language="0" MajorVersion="1" MinorVersion="1" HelpDirectory="INSTALLDIR">
          <Interface Id="{0F0BFAE2-4C90-11D1-82D7-0004AC368519}" Name="IVim" ProxyStubClassId="{00020424-0000-0000-C000-000000000046}" ProxyStubClassId32="{00020424-0000-0000-C000-000000000046}" />
          <Class Id="{0F0BFAE1-4C90-11d1-82D7-0004AC368519}" Context="LocalServer32" Version="Vim.Application.1">
            <ProgId Id="Vim.Application.1">
              <ProgId Id="Vim.Application" />
            </ProgId>
          </Class>
        </TypeLib>
        <?endif?>
        ]]>
      </xsl:text>
    </xsl:copy>
  </xsl:template>

</xsl:transform>
